name: Parallel Test Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  db-test-run:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run DB Tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:dbfile

  login-run:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Login Tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:login
