name: parallal build
'on': push
jobs:
  cypress-run1:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with: 'command:npm run test:dbfile'
  cypress-run2:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with: 'command:npm run test:login'
